import { FiMinus, FiPlus, FiTrash2, FiX } from "react-icons/fi";
import { useCart } from "../context/CartContext";
export default function CartDrawer({ open, onClose }) {
 const {items,updateQuantity,removeItem,subtotal}=useCart(); const delivery=items.length?150:0;
 return <><button aria-label="Close cart" onClick={onClose} className={open?"fixed inset-0 z-40 bg-black/40 backdrop-blur-sm":"hidden"}/>
 <aside className={`fixed right-0 top-0 z-50 h-full w-full max-w-md transform bg-[#fffaf3] p-5 shadow-2xl transition duration-300 dark:bg-slate-950 dark:text-white ${open?"translate-x-0":"translate-x-full"}`}>
 <div className="flex items-center justify-between"><div><p className="text-sm font-bold text-emerald-600">Your basket</p><h2 className="text-2xl font-black">Market cart</h2></div><button onClick={onClose} className="grid h-10 w-10 place-items-center rounded-full bg-white dark:bg-slate-800"><FiX/></button></div>
 <div className="mt-6 space-y-3">{!items.length&&<div className="rounded-3xl bg-white p-8 text-center text-slate-500 dark:bg-slate-900">Your basket is empty. Add something fresh 🌿</div>}
 {items.map(item=><div key={item.id} className="flex gap-3 rounded-3xl bg-white p-3 dark:bg-slate-900"><img src={item.image_url||"https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=300&q=80"} alt="" className="h-20 w-20 rounded-2xl object-cover"/><div className="flex-1"><div className="font-black">{item.name}</div><div className="text-xs text-slate-500">{item.vendor_name}</div><div className="mt-2 font-black text-emerald-600">KSh {Number(item.price).toLocaleString()}</div></div><div className="flex flex-col items-end justify-between"><button onClick={()=>removeItem(item.id)} className="text-slate-400 hover:text-red-500"><FiTrash2/></button><div className="flex items-center gap-2 rounded-full bg-slate-100 p-1 dark:bg-slate-800"><button onClick={()=>updateQuantity(item.id,item.quantity-1)} className="grid h-7 w-7 place-items-center"><FiMinus/></button><span className="text-sm font-bold">{item.quantity}</span><button onClick={()=>updateQuantity(item.id,item.quantity+1)} className="grid h-7 w-7 place-items-center"><FiPlus/></button></div></div></div>)}</div>
 {!!items.length&&<div className="absolute bottom-0 left-0 right-0 border-t bg-white p-5 dark:border-white/10 dark:bg-slate-900"><div className="flex justify-between text-sm"><span>Items</span><span>KSh {subtotal.toLocaleString()}</span></div><div className="mt-2 flex justify-between text-sm"><span>Estimated delivery</span><span>KSh {delivery}</span></div><div className="mt-4 flex justify-between text-xl font-black"><span>Total</span><span>KSh {(subtotal+delivery).toLocaleString()}</span></div><button className="mt-4 w-full rounded-2xl bg-emerald-600 py-4 font-black text-white">Continue to checkout</button><p className="mt-2 text-center text-xs text-slate-500">Pickup removes the delivery fee at checkout.</p></div>}</aside></>;
}